### ISSUE TITLE
Confluence 5.7.x

### ISSUE THREAD

**Issue by huang63** [chauth/confluence_http_authenticator#27]
Hi,

Has anyone successfully used the latest release of this add-on with Confluence 5.7.x?

When I tried it, here are what I got:
1. The redirect from the login URL did not work properly -- Instead of going to Shibboleth login page, I got page not found error.
2. If a valid Shibboleth session existed, the session authenticated the user into Confluence. Also, if the user did not exist, it will be created automatically as expected.

Thanks.

**Comment by garysweaver** [comment]
@huang63 I noticed that you closed this issue. Did you resolve it?

**Comment by huang63** [comment]
Hi Gary,

Thanks for the email.

The problem was caused by the extra settings of /Shibboleth.sso in
shib.conf for Apache. The add-on worked after I removed those and restart
Apache.

**Comment by faribakes** [comment]
could you give me the details of what you removed? I still have issues with 5.7 version and shibbolet.

**Comment by faribakes** [comment]
@huang63  could you give me the details of what you removed.
Under apache conf file I do not see any reference but under shibbolet I see and i do not know which one should be removed if any:
./shibboleth2.xml:            handlerURL="/Shibboleth.sso" handlerSSL="true"
./shibboleth2.xml:            exportLocation="http://localhost/Shibboleth.sso/GetAssertion"
./apache.config:<Location /Shibboleth.sso>
./apache22.config:<Location /Shibboleth.sso>
./apache24.config:<Location /Shibboleth.sso>
./apache2.config:<Location /Shibboleth.sso>
./metagen.sh:      <disco:DiscoveryResponse Binding="urn:oasis:names:tc:SAML:profiles:SSO:idp-discovery-protocol" Location="https://$h/Shibboleth.sso/DS" index="$count"/>
./metagen.sh:      <disco:DiscoveryResponse Binding="urn:oasis:names:tc:SAML:profiles:SSO:idp-discovery-protocol" Location="http://$h/Shibboleth.sso/DS" index="$count"/>
./metagen.sh:    <md:SingleLogoutService Binding="${SLO[$count]}" Location="https://$h/Shibboleth.sso/SLO/${SLOLOC[$count]}"/>
./metagen.sh:    <md:SingleLogoutService Binding="${SLO[$count]}" Location="http://$h/Shibboleth.sso/SLO/${SLOLOC[$count]}"/>
./metagen.sh:    <md:ManageNameIDService Binding="${SLO[$count]}" Location="https://$h/Shibboleth.sso/NIM/${SLOLOC[$count]}"/>
./metagen.sh:    <md:ManageNameIDService Binding="${SLO[$count]}" Location="http://$h/Shibboleth.sso/NIM/${SLOLOC[$count]}"/>
./metagen.sh:    <md:AssertionConsumerService Binding="${ACS[$count]}" Location="https://$h/Shibboleth.sso/${ACSLOC[$count]}" index="$((index+1))"/>
./metagen.sh:    <md:AssertionConsumerService Binding="${ACS[$count]}" Location="http://$h/Shibboleth.sso/${ACSLOC[$count]}" index="$((index+1))"/>

**Comment by huang63** [comment]
Hi,

I removed the the block of </Shibboleth.sso> from /etc/httpd/conf.d/shib.conf.

**Comment by faribakes** [comment]
This is what I have for shib.conf and no reference to Shibboleth.sso:
LoadModule mod_shib /usr/lib64/shibboleth/mod_shib_22.so

<IfModule mod_alias.c>
  <Location /shibboleth-sp>
    Allow from all
  </Location>
  Alias /shibboleth-sp/main.css /usr/share/doc/shibboleth-2.4.3/main.css
  Alias /shibboleth-sp/logo.jpg /usr/share/doc/shibboleth-2.4.3/logo.jpg
</IfModule>

<Location /confluence>
  AuthType shibboleth
  ShibRequestSetting requireSession 1
  ShibUseHeaders On
  require entitlement urn:mace:xxxx:xxxxx
</Location>

**Comment by faribakes** [comment]
some of the lines like <location: did not copy in the above.

**Comment by huang63** [comment]
Hi,

Here is what I have used:

LoadModule mod_shib /usr/lib64/shibboleth/mod_shib_22.so

  <IfModule mod_alias.c>
    <Location /shibboleth-sp>
      Allow from all
    </Location>
    Alias /shibboleth-sp/main.css /usr/share/doc/shibboleth-2.3.1/main.css
    Alias /shibboleth-sp/logo.jpg /usr/share/doc/shibboleth-2.3.1/logo.jpg
  </IfModule>

  <Location />
    AuthType shibboleth
    ShibCompatWith24 On
    ShibRequestSetting requireSession 0
    require shibboleth
    ShibUseHeaders On
  </Location>

**Comment by faribakes** [comment]
Thanks for the reply but I had already got it working without any changes to shibboleth. Turns out I had to change the tomcat path in server.xml so shibboleth finds the page.
