### ISSUE TITLE
Issues with basic http authentication(Confluence 5.8.5, plugin 2.6.0)

### ISSUE THREAD

**Issue by varidots** [chauth/confluence_http_authenticator#31]
Basic Authentication appears to be entirely broken at the moment. I'm writing the issue down just so that it gets tracked, might attempt to resolve it myself if I can allocate the time for figuring out how the plugin works.

Issue:
With the SSO plugin enabled:
* Attempting to use the REST API with incorrect credentials returns a status code of 401 with no content in the body. 
* Attempting to use the REST API with correct credentials returns a status code of 401 with the Tomcat AUTHENTICATED_FAILED error message in the body.

Without the SSO plugin enabled:
* Attempting to use the REST API with incorrect credentials returns a status code of 401 with the Tomcat AUTHENTICATED_FAILED error message in the body.
* Attempting to use the REST API with correct credentials results in the expected return value.

Replicating the issue:
1. Enable the confluence_http_authenticator plugin
2. Create the user api_test with a password of test in Confluence
3 .Execute the command curl -u api_test:test  https://confluence/wiki/rest/space/ts
> HTTP Status 401 - Basic Authentication Failure - Reason : AUTHENTICATED_FAILED

4. Disable the confluence_http_authenticator plugin
5. Execute the command curl -u api_test:test  https://confluence/wiki/rest/space/ts

>No space found with key : ts

This is probably the same issue as https://github.com/chauth/confluence_http_authenticator/issues/30, but a bit more of a generic case.

**Comment by garysweaver** [comment]
Feel free to have at it. If you have any trouble with setting up the build, let me know. I mentioned a possible fix in #30.

**Comment by garysweaver** [comment]
Same as #30. Let's track it there.
