### ISSUE TITLE
Issues with .replace pairwise regex

### ISSUE THREAD

**Issue by sploittastic** [chauth/confluence_http_authenticator#38]
Good morning,

I'm not sure if the pairwise regex is just not supporting the replacement of spaces and periods or if I'm just hosing the syntax; I feel like I've tried enough variations that I should have at least accidentally gotten it working by now...

I was able to remove (replace with null) letters, but unlike the example this only works when putting parenthesis around them:
remoteuser.replace=(J),,

For the removal of periods, I've tried:
.,,
(.),,
\.,,
(\.),,
(\\.),,
\\.,,
"\."
[.],,

And none seem to match.  I've been trying to figure out the matching of periods since it's easier to replicate than cases of space in the username (which aren't supported by confluence).  I've tried various things for spaces as well.

Can anyone point me in the right direction of how to get spaces and periods to match, or is this a bug?

Thank you!
Jeffrey

**Comment by gmkll** [comment]
a period in a regex is reserved word, you have to escape it. I have added a test.

**Comment by sploittastic** [comment]
Thanks, I was able to get it working with your assistance.  Just out of curiosity, does .replace reply on the map functions or can the line with .replace be used standalone?

Thank so much for your assistance!
Jeffrey

**Comment by gmkll** [comment]
I am not exactly sure about, what you mean, but you could surely use replace (replaceAll) with any String, if you provide a valid regex pattern, which is why I checked first, that it compiles. Where you think a .replace would make sense?
