### ISSUE TITLE
Confluence-5.10.x Support

### ISSUE THREAD

**Issue by ellestad** [chauth/confluence_http_authenticator#40]
The plugin works with confluence-5.10.x, but a "User Administrator Health Check" error appears to Confluence Administrators, even with a configured local administrator with appropriate permissions.

"Confluence has an enabled internal user directory, however it's administrator user does not exist or is disabled."

**Comment by theseal** [comment]
I don't think this is related to Confluence 5.10.x.
We have Confluence 5.8.18 and have the same error message. My quess is that this comes from one of the Support Tool Plugin that might have been upgraded in our installation and probably is the lastest in yours.

Still a problem, but should/could it be handled by this plugin?

**Comment by ellestad** [comment]
This can be closed. We heard back from Atlassian and it is a problem with the health check, not confluence_http_authenticator. We have over 17,400 users in our internal directory. From Atlassian: "There seems to be a limit on the SELECT query that retrieves all the internal directory users such that the administrators are excluded along with thousands of others, and so when Confluence iterates through the set it doesn't find the administrators."
