### ISSUE TITLE
Dynamic Roles

### ISSUE THREAD

**Issue by leonizm** [chauth/confluence_http_authenticator#43]
Hello,

I'm using 2.2.0.jar file of the authenticator for Confluence (5.0.3) and I can't get the dynamic role to work.  I'm using the AttributeResolver below to get a 3 character code which represents the Confluence group the logged in user should be put into and for whatever reason I can not get it to work.  The AttributeResolver takes the attribute "threeCharUser" like "BUC-COLLINL" and transform it to "BUC" and assigned it to "userDefaultCampusGroup".  So any user with userDefaultCampusGroup value "BUC" should be placed in the Confluence group named "BUC". 

(in shibboleth2.xml)
`        <AttributeResolver type="Transform" source="threeCharUsername">
            <Regex match="-(.*)" dest="userDefaultCampusGroup">$2</Regex>
        </AttributeResolver>
`
(in attribute-map.xml
`    <Attribute name="threeCharUsername" nameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic" id="threeCharUsername"/>
    <Attribute name="EMAIL" nameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic" id="email"/>
    <Attribute name="fullName" nameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic" id="fullname"/>
	<Attribute name="userDefaultCampusGroup" nameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic" id="defaultdynamicgroup"/>`

(in remoteUserAuthencator.properties)
header.dynamicroles.attributenames=defaultdynamicgroup, userDefaultCampusGroup
header.dynamicroles.BUC=BUC
header.dynamicroles.wes=WES

Thanks,
Leon

**Comment by gmkll** [comment]
May be this is somewhat scrambled in the docs, shouldn´t it be `dynamicroles.header` in rUA.properties, cft.  code in s.c.a.s.ShibAuthConstants.java ?

**Comment by leonizm** [comment]
gmkll,

Thank you for the reply.  I'm new to this and some parts of the documentation is not clear to me (and it could just be my stupidity).  In parts of the documentation I see header.dynamic and other parts i see dynamicroles.header and I have tried both and none seems to be working for me so I'm not sure what I'm doing wrong and where.

Thanks,
Leon

**Comment by leonizm** [comment]
gmkll,

I may have spoken too soon.  Going off what you suggested I may now be seeing some progress and I think I might be close to getting this working the way I would like it to work.

Thanks,
Leon

**Comment by leonizm** [comment]
The below is what now works for me, for what I wanted.

###regex###
header.dynamicroles.attributenames=userDefaultCampusGroup
dynamicroles.header.userDefaultCampusGroup=BUC, WES

dynamicroles.mapper.WES.match=(.*)
dynamicroles.mapper.BUC.match=(.*)

**Comment by gmkll** [comment]
Solved - super! Docs have to be improved, though..
