### ISSUE TITLE
Your session has expired. Please reload the page to try again.

### ISSUE THREAD

**Issue by pescobar** [chauth/confluence_http_authenticator#45]
Hi

I have configured the shibboleth authentication with the latest confluence release 6.5 and it seems to be working correctly to login. I can login as an admin user and move around and do any desired configuration change but when I try to do `Spaces >> create new space` I get a message `Your session has expired. Please reload the page to try again.`

If I try to reload the page it doesn't solve the problem. After the error message my session is still active, I am not logged out. I am testing with an account in the groups "confluence-administrators" and "confluence-users"

Is this a problem with the plugin and the latest confluence version or is it because of a wrong configuration?

**Comment by scantor** [comment]
I wouldn't be at all surprised if those kinds of identifier formats break lots of things. They're highly unsuitable for a wiki. You should require a non-directed identifier that's in a more reasonable form. Don't fall into that trap when you're just starting out. That said, that identifier format is 100% on you, you decide how to serialize that triple into a string.

**Comment by pescobar** [comment]
thanks for you suggestion @scantor 

I have updated my config file `remoteUserAuthenticator.properties` to switch from `header.remote_user=REMOTE_USER` (which was providing that long url as Username) to `header.remote_user=mail` 

Now the accounts created in Jira have the email as username and the problem is solved.

Thanks!
