### ISSUE TITLE
Supported Confluence versions

### ISSUE THREAD

**Issue by pqvindesland** [chauth/confluence_http_authenticator#49]
Hi

Apologies I tried to post to the google group and the google email list but I am getting a error message saying that it both of them doesn't exist.

I'm just wondering if this plugin supports Confluence version 6.x or is 5.x the only choice? if no would there be a plan to support version 6 and if so how soon?

Regards

**Comment by gmkll** [comment]
PR #48 claims to support confluence v6.8.3 providing a compatible binary build with j8_121 instead of  the j8_31 last release build, which seems not to be compatible with 6.8.3.

**Comment by pqvindesland** [comment]
Since it's going into production then it would have been nice with more official support, when you say  j8_121, do you mean Java 8?

**Comment by gmkll** [comment]
yes. Though the plugin has still java compile target 1.7, it was compiled with Java version 1.8 since at least v.2.7.2. Confluence announces (at least since v6.4), that Java version 1.8.0_31 (and _25) is not supported, which may explain PR #48 (cft. comments there more information). Does this help?

**Comment by pqvindesland** [comment]
Many thanks for then clarification, when is it releases as 2.7.3?

**Comment by gmkll** [comment]
I released it right now!
