### ISSUE TITLE
Disabling access for users which are not in configured groups

### ISSUE THREAD

**Issue by kristapsm** [chauth/confluence_http_authenticator#50]
Hi there,

First of all thanks for such a great plugin, works really well.
Recently we noticed that all users who are able to authenticate against our company SSO login screen are able to log-in in confluence/jira even though they are not members of specified groups coming from Shibboleth.

To explain more, let me make an example:
* I create groupA in our SSO provider and add userA in this group
* I map this groupA with jira-users internal JIRA group
* userA is able to authenticate against company SSO and is created in JIRA and is added to jira-users group
* userB is a part of company so he is also able to authenticate against company SSO, but he is not a member of groupA
* userB authenticates against SSO and is created in JIRA, but is not added to any internal group

This does not make JIRA safe any more as userB is able to search Issues and create Issues etc.
So question - is it possible to restrict access for userB in this case so the user wont even be created for him in JIRA/Confluence?

By default I think JIRA uses permission scheme to allow to see/create issues for Any logged in user. I believe this can be restricted by modifying permission scheme and granting access to Groups only such as jira-users, but would like to know if its possible to do it without modifying permission scheme but with remoteUserAuthenticator instead?

Regards,
Kristaps

**Comment by martintbis** [comment]
Hi Kristaps,

please verify that you [disabled the default group] function  (https://github.com/chauth/confluence_http_authenticator/blob/master/conf/remoteUserAuthenticator.properties#L28) for authenticated users.

We are using a setup with KeyCloak as SSO system and Active Directory as User store - it works as expected - only users with the correct membership within AD are allowed to login into confluence.

Regards,
Martin

**Comment by gmkll** [comment]
seems to be resolved by last [comment](https://github.com/chauth/confluence_http_authenticator/issues/50#issuecomment-408228415).
