### ISSUE TITLE
Support help?

### ISSUE THREAD

**Issue by pqvindesland** [chauth/confluence_http_authenticator#51]
Is there any specific place where I can help some help with this plugin?

I'm updating from Confluence version 5.4.4 to 6.8.3 on the old server we are using remoteUserAuth-2.5.0.jar so I grabbed the remoteUserAuthenticator.properties from the old server and scp'ed it to the new server then downloaded remoteUserAuth-2.7.3.jar copied remoteUserAuthenticator.properties to /opt/atlassian/confluence/confluence/WEB-INF/classes/ and remoteUserAuth-2.7.3.jar to /opt/atlassian/confluence/confluence/WEB-INF/lib/ restart confluence but then confluence stops working, 

The Java version that comes with Confluence 6.8.3 is used.

Do you any any suggestions? is there any files I have missed pulling over or is the remoteUserAuthenticator.properties file in use on the old Confluence server now compatible with  remoteUserAuth-2.7.3?
[atlassian-confluence-1.log](https://github.com/chauth/confluence_http_authenticator/files/2175620/atlassian-confluence-1.log)

**Comment by gmkll** [comment]
Are you sure, that's the problem? The log does not point to anything related. At least there is no line like this ..

>  INFO [localhost-..] [confluence.authentication.shibboleth.ShibAuthConfigLoader] getShibAuthConfiguration Setting config file name ..

which I wouldexpect (after springframework.web.context.ContextLoader )..

**Comment by pqvindesland** [comment]
If I remove both the plugin files and start up Confluence again then it starts with no problems., I forgot to mention that it's on a Centos 6 box.

**Comment by gmkll** [comment]
What's the output, if you set the log level to debug (for shibauth.confluence.authentication.shibboleth)?

**Comment by pqvindesland** [comment]
Sweet many thanks for all the assistance, I got it sorted out, the jar file was corrupted and once I changed seraph-config.xml to <authenticator class="shibauth.confluence.authentication.shibboleth.RemoteUserAuthenticator"/> it all started to work :)
