### ISSUE TITLE
Add option to not truncate HTTP header

### ISSUE THREAD

**Issue by lebedik** [chauth/confluence_http_authenticator#52]
Currently we have a restriction with following description:
https://github.com/chauth/confluence_http_authenticator/blob/master/conf/remoteUserAuthenticator.properties#L50-L51

It will be grate if king of option will be available to read full header, even if contain comma or semicolon.

**Comment by gmkll** [comment]
Which header do you need multiple-valued? For roles the list is already provided, of course, but not for e-mails, username, fullname(s), as you could only set it to a single value: Attlasian [userbuilder](https://docs.atlassian.com/atlassian-crowd/3.2.1/com/atlassian/crowd/embedded/impl/ImmutableUser.Builder.html) method called in [updateUser](https://github.com/chauth/confluence_http_authenticator/blob/master/src/main/java/shibauth/confluence/authentication/shibboleth/RemoteUserAuthenticator.java#L340-L364) or check calls to toListOfNonEmptyStringsDelimitedByCommaOrSemicolon [here](https://github.com/chauth/confluence_http_authenticator/blob/master/src/main/java/shibauth/confluence/authentication/shibboleth/RemoteUserAuthenticator.java),

**Comment by lebedik** [comment]
We did try to map username coming from header in following format:
`C=CODE, O=ORG, CN=CommonName` and match `CommonName` by apply regexp, but unfortunately authentication only return `C=CODE` for now

**Comment by gmkll** [comment]
Ok, you get not just the cn from your SSO provider, but part of or entire DN in remote_user header. Might be, there is a reason for that? If this is a not uncommon use case, it might be added (e.g. defining a regex extractor strategy)...

**Comment by lebedik** [comment]
Right, it's exactly our case

**Comment by gmkll** [comment]
Do you mind providing a PR? Should be quite straightforward (if a (new) configuration parameter is set, e.g. username.regex providing a matching group, this is evaluated) - just for username ?

**Comment by gmkll** [comment]
but check first `remoteuser.map.remoteusermap.match`  and method `createSafeUserid,` if this might suffice.

**Comment by cryomi** [comment]
Hi, folks,
Added PR #53 to fix this issue.

**Comment by gmkll** [comment]
#53 merged into master trunk.
