### ISSUE TITLE
Atlassian archiving "HTTP Authenticator for Confluence" add-on in the Marketplace

### ISSUE THREAD

**Issue by bananastalktome** [chauth/confluence_http_authenticator#56]
I was granted access to the add-on in the Atlassian Marketplace several years ago when I made a few documentation related changes. Though I do not feel I am a qualified contributor to make decisions regarding the development future of this project, I wanted to pass along an automated email I received from Atlassian:

> Hi there,
We noticed that [HTTP Authenticator for Confluence](https://marketplace.atlassian.com/manage/apps/4863)  is out of date and due for automatic archival in 30 days. You can add a  version with updated compatibility to keep your add-on current in the  Marketplace and avoid archival.
We [routinely archive add-ons](https://developer.atlassian.com/x/h4QWAQ) to keep the selection in the Marketplace current. We archive add-ons when more than a year has passed since the supported [Atlassian application's end-of-life date](https://confluence.atlassian.com/display/Support/Atlassian+Support+End+of+Life+Policy). You can add a new version to keep HTTP Authenticator for Confluence in the Marketplace.
If you don't [add a new version](https://marketplace.atlassian.com/manage/apps/4863), your  add-on will be automatically archived in 30 days. This means that your  add-on won't appear in search results or browsing lists on the Atlassian  Marketplace. However, versions of your add-on will be available to  download on our [archive page](https://marketplace.atlassian.com/archive).
 
Cheers,
The Marketplace Team

**Comment by gmkll** [comment]
just logged on and indeed could not find any results in current marketplace or in archive for search term "http authenticator" and produhct confluence. Should we newly apply? If you get a result, could you upload the most recent release?

**Comment by bananastalktome** [comment]
Although I do have access to the admin area for this add-on in the Marketplace, I don't think I've ever used it prior to today. If @garysweaver is still around to give the okay, I can grant you admin access in the Marketplace since you are much more involved in this project and better equipped to keep the marketplace listing updated than I am.

**Comment by bananastalktome** [comment]
Since it seems Gary may not be active in this project any longer, if @vladimir-mencl-eresearch or @kevinfoote (both admins for this add-on in the Atlassian Marketplace) could give the okay, I can add @gmkll there as well.

**Comment by kevinfoote** [comment]
@bananastalktome gh access is fine w/ me

**Comment by vladimir-mencl-eresearch** [comment]
And fine with me too.

I see this is project is an orphan with several "uncles" willing to help but otherwise busy... I also got access to the plugin through several contributions in the past, and without feeling authorised enough to make decisions, I've been also looking at this as @bananastalktome  - "someone should do something, I just don't think I'm the right choice".

Thanks @bananastalktome and @gmkll for the initiative.

And we should perhaps empower willing contributors to do more and take on the Maintainer hat...

**Comment by bananastalktome** [comment]
Thanks, what is a good email address for me to use to get you access, @gmkll ?

**Comment by gmkll** [comment]
Best would be georg.kallidisatfu-berlindotde. Thanks! Although I jumped into to prepare a release lately, I come into play only occasionally. 

On August 21, 2019 1:43:33 PM GMT+02:00, William Schneider <notifications@github.com> wrote:
>Thanks, what is a good email address for me to use to get you access,
>@gmkll ?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/chauth/confluence_http_authenticator/issues/56#issuecomment-523420304

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bananastalktome** [comment]
@gmkll Sorry for the trouble in getting this taken care of, apparently I can't just invite someone to be an admin, they need to have an atlassian account already. Can you please go to the atlassian marketplace, create an account (using that email address), and then let me know, I can then try to grant you admin status.

**Comment by gmkll** [comment]
Ok, the account I registered is georg.kallidisatcedis.fu-berlin.de. 

On August 21, 2019 9:03:26 PM GMT+02:00, William Schneider <notifications@github.com> wrote:
>@gmkll Sorry for the trouble in getting this taken care of, apparently
>I can't just invite someone to be an admin, they need to have an
>atlassian account already. Can you please go to the atlassian
>marketplace, create an account (using that email address), and then let
>me know, I can then try to grant you admin status.
>
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/chauth/confluence_http_authenticator/issues/56#issuecomment-523605493

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bananastalktome** [comment]
Sounds great, I've made you an admin for this on the Atlassian marketplace site.

**Comment by gmkll** [comment]
The plugin v2.7.3 is [released on the Atlassian Marketplace](https://marketplace.atlassian.com/manage/apps/4863/versions), but it's still hidden and could not be found (already contacted Marketplace Vendor Support).

**Comment by gmkll** [comment]
last remark: It's now [public](https://marketplace.atlassian.com/search?query=HTTP%20Authenticator%20for%20Confluence) again! CHeck the
