### ISSUE TITLE
Confluence 7.12 throws Exception in updateUser 

### ISSUE THREAD

**Issue by gmkll** [chauth/confluence_http_authenticator#61]
A new user could be created and log in, but details (fullname,..) are not set i updae:

`ERROR [confluence.authentication.shibboleth.RemoteUserAuthenticator] updateUser Couldn't update user xxxx
java.lang.NoSuchMethodError: 'com.atlassian.crowd.embedded.api.User com.atlassian.crowd.embedded.impl.ImmutableUser$Builder.toUser()'
	at shibauth.confluence.authentication.shibboleth.RemoteUserAuthenticator.updateUser(RemoteUserAuthenticator.java:368)
	at shibauth.confluence.authentication.shibboleth.RemoteUserAuthenticator.getUser(RemoteUserAuthenticator.java:993)
`

**Comment by gmkll** [comment]
after recompilation with java 11 and maven.compiler.source/target set to 1.8 (and -Dconfluence.version=7.13.2) the error is gone.

**Comment by vladimir-mencl-eresearch** [comment]
I am happy to confirm the new release 2.7.4 fixes this issue (as well as #62 ).  Thanks @gmkll for cutting the release!
